### PR TITLE
fix: 108 109 110 api changes after firmware review

### LINKED ISSUE #108: Create a new method to lookup fcts by name

### LINKED ISSUE #109: rename `customData` key on the population of the IO node functions to `fctData`
To be more clear and to allow passing in data for the slot to we want a change in the logic in the mutators that automatically create IO nodes on empty slots:
from 
```js 
{
  ...customData,
}
```

to
 ```js
  ...customData, // we need it until firmware has updated their code
  ...fctData
  slots: [{
  name: ...,
  unit: ...,
  ...
  ...slotData

  }]
```
- [ ] extend the options that can be passed in as `options` with tow new keys: `fctData` and `slotData`
- [ ] when `customData` is provided, show a deprecation warning

### LINKED ISSUE #110: `ports` should only be allowed on sensors and `actuators`
- [ ] set the default value for `ports` only on functionalities of the type `Sensor` and `Actuator`
- [ ] make `ports` an optional property on the other functionalities (we can't remove it yet because the DB has graphs with functionalities that are neither sensor nor actuator and have `ports` on them

### LINKED ISSUE #113: change default `publishIntervalMs` value for `IntervalOut` node in fct-graph  to 1000 (ms) (see `DEFAULT_PUBLISH_INTERVAL` in `IntervalOut.js`)

### PR DESCRIPTION
**Pull request by vdiezel**
closes #108 
closes #109 
closes #110 
closes #113 

I decided not to allow passing data for the slot next to `fctData` when generating IONodes. Couldn't think of any key somebody would want to set. `name` should not be allowed, unit will be `any` soon. `min, max, defaultValue` don't make any sense and dataStreams should be created via the connection API.

### CODE REVIEW

File: src/fctGraph/Utils/mutators/addOutputFctForOutSlotWhichHasNone.js [hunk 1]
```diff
@@ -41,6 +41,10 @@ function safeAddOutputFctAndConnect(fctGraph, outSlot, outputFct) {
 function addOutputFctForOutSlotWhichHasNone(fctGraph, outSlot, subTypeClass, opts) {
   assertPrerequisites(fctGraph, outSlot)
 
+  if ("customData" in opts) {
+    console.warn('DEPRECATION WARNING: "customData" key is deprecated. Please use "fctData" instead')
+  }
+
```
Comment (DanielSeehausen) [inline src/fctGraph/Utils/mutators/addOutputFctForOutSlotWhichHasNone.js:46]: I would even consider throwing here instead of letting execution continue. if one used `customData`, they will end up with a result that doesn't look like they expected.

**Review by DanielSeehausen — APPROVED** [review]

File: src/fctGraph/Utils/mutators/addOutputFctForOutSlotWhichHasNone.js (hunk 1 above)
Comment (vdiezel) [reply src/fctGraph/Utils/mutators/addOutputFctForOutSlotWhichHasNone.js:46]: But that would also break our hambda implementation. 

`customData` usage hasn't changed yet. If they pass it, it will be applied.
